---

- name: Deploy logstash config
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: logstash
    mode: '0644'
  notify: Restart Logstash
