---

- name: Create grafana user
  ansible.builtin.user:
    name: grafana
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Add grafana gp key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add grafana APT repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present