---

- hosts: elk
  become: yes
  roles:
    - { role: elasticsearch, tags: ['elasticsearch', 'elk'] }
    - { role: logstash, tags: ['logstash', 'elk'] }
    - { role: kibana, tags: ['kibana', 'elk'] }

- hosts: clients
  become: yes
  roles:
    - { role: filebeat, tags: ['filebeat', 'clients'] }
    - { role: node_exporter, tags: ['node_exporter', 'clients'] }

- hosts: prometheus
  become: yes
  roles:
    - { role: prometheus, tags: ['monitoring', 'prometheus'] }
    - { role: grafana, tags: ['monitoring', 'grafana'] }