#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/kibana

- name: Installation tasks
  ansible.builtin.import_tasks: install.yml
  tags: 
    - kibana_install

- name: Configuration tasks
  ansible.builtin.import_tasks: config.yml
  tags: 
    - kibana_config

- name: Service tasks
  ansible.builtin.import_tasks: service.yml
  tags: 
    - kibana_service