---

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Download node_exporter archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.0/node_exporter-1.8.0.linux-arm64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Create node_exporter directory
  ansible.builtin.file:
    dest: /opt/node_exporter
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: Extract node_exporter archive
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/node_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: Copy node_exporter binary
  ansible.builtin.copy:
    src: /opt/node_exporter/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    remote_src: yes
    mode: '0755'