---

- name: Create systemd unit file for node_exporter
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd deamon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start node_exporter service
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: yes