---

- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Create prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus
    - /opt/prometheus

- name: Download prometheus archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.51.1/prometheus-2.51.1.linux-arm64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    mode: '0644'

- name: Extract prometheus archive
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: Copy prometheus binary to /usr/local/bin
  ansible.builtin.copy:
    remote_src: yes
    src: /opt/prometheus/prometheus
    dest: /usr/local/bin/prometheus
    mode: '0755'

- name: Copy promtool binary to /usr/local/bin
  ansible.builtin.copy:
    remote_src: yes
    src: /opt/prometheus/promtool
    dest: /usr/local/bin/promtool
    mode: '0755'



