---

- name: Create systemd unit file for prometheus
  ansible.builtin.copy:
    dest: "/etc/systemd/system/prometheus.service"
    content: |
      [Unit]
      Description=Prometheus Monitoring
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.console.templates=/opt/prometheus/consoles \
        --web.console.libraries=/opt/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd to pick up new prometheus service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes